### ISSUE TITLE
Interop with Flux and Mono types

### ISSUE THREAD

**Issue by bbarker** [zio/interop-reactive-streams#309]
Hi, 

I was wondering if interop with the Flux and Mono types from https://projectreactor.io is something that might be considered for this repository - in particular, it would be great to be able to convert a `ZStream` to `Flux` or `Mono` and vice versa. Maybe this is already easy enough with the existing interfaces. Just wanted to check before taking a stab at it, and if it works out, is it OK to submit a PR with this support enabled?

**Comment by bbarker** [comment]
As near as I can tell, this should work out of the box - but one thing that is preventing me from testing it seems to be the fact that `.toStream(Int)` is actually a method on `Flux` itself, albeit with a different return type:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/916366/158248536-d586bb05-3b1c-4ab9-8e8f-fb1bb02fe86b.png">
So as you can see in the screenshot, I'm not getting back a ZStream, despite having:

```scala
import zio.interop.reactivestreams.*
```

I'm not sure if there's a good approach to this, other than perhaps adding an alias to (or renaming) `publisherToStream.toStream` to something like `publisherToStream.toZioStream`.

I can work around it by using it as a regular class, but it is a bit unwieldy:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/916366/158249335-f36dd29f-ab4d-48f6-9a15-01abcb404503.png">

**Comment by calvinlfer** [comment]
We ended up doing the following upcast to work around the naming clash:
```scala
import org.reactivestreams.Publisher
import reactor.core.publisher.{ Flux, Mono }
import zio.interop.reactivestreams._
import zio.stream.ZStream

object InteropCheck {
  val flux: Flux[Int] = Flux.just(1, 2, 3)
  val mono: Mono[Int] = Mono.just(1)

  val monoIsAPublisher: Publisher[Int] = mono
  val fluxIsAPublisher: Publisher[Int] = flux

  val mStream: ZStream[Any, Throwable, Int] = monoIsAPublisher.toStream()
  val fStream: ZStream[Any, Throwable, Int] = fluxIsAPublisher.toStream()
}
```

**Comment by bbarker** [comment]
Yeah, based on @calvinlfer's approach, the above code snippet looks like this, which is a definite improvement:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/916366/158252752-27fd7f46-bcbd-4e0a-a20c-3caff05f5003.png">

**Comment by runtologist** [comment]
I guess we could rename the methods to `toZIOStream` and `toZIOSink` to avoid name clashes in 2.0. Do you want to open a PR against the `series/2.x` branch?

**Comment by runtologist** [comment]
If you need this for 1.0, then I propose copying `package.scala` to your codebase and namespace, renaming the extension methods, and importing them from the copy.

**Comment by calvinlfer** [comment]
we can open an MR for 2.x - thanks @runtologist !

**Comment by runtologist** [comment]
v2.0.0 with the renamings proposed here has been released. Thanks again for bringing this up!
