### ISSUE TITLE
Question: Does it pass the reactive streams TCK?

### ISSUE THREAD

**Issue by Petikoch** [zio/interop-reactive-streams#86]
Hi,

I was wondering if you did run your implementation against the reactive streams TCK?
https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck

Thanks for your answer & best regards,
Peti

**Comment by runtologist** [comment]
Dear Peti,

The test suite includes all TCK blackbox and whitebox tests. We use a thin wrapper to be able to run the TestNG suites via zio-test.

Cheers,
Simon

**Comment by Petikoch** [comment]
Thank you Simon for the answer, excellent! 

PS: I came to this question, because a friend of mine (@pme123) is so passionate about Scala and especially ZIO and pushed me to have a closer look at it. I'm more the "Kotlin / RxJava / coroutines" guy. One of my first thoughts was "well, this looks a lot like RxJava" and then "does it implement also the reactive-stream API?" :-)
